const estudiantes = {
  "61280746": {
    "DNI": "61280746",
    "NOMBRE Y APELLIDO": "ACHAHUANCO SOTO, Juan Policarpo",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "18",
    "MS EXCEL": "13",
    "GESTION DE NEGOCIOS ": "17",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "70756319": {
    "DNI": "70756319",
    "NOMBRE Y APELLIDO": "APAZA MAMANI, Giner Victor",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "17",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "NP",
    "APROBADAS": "5",
    "DESAPROBADAS": "1",
    "CONDICION": "DESAPROBADO"
  },
  "77223639": {
    "DNI": "77223639",
    "NOMBRE Y APELLIDO": "BORDA RUGEL, Patric Eliver",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "19",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "15",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "60859159": {
    "DNI": "60859159",
    "NOMBRE Y APELLIDO": "CANELOS GONZALES, Dayra Lady",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "13",
    "MS WORD": "1",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "1",
    "DESAPROBADAS": "5",
    "CONDICION": "DESAPROBADO"
  },
  "61079943": {
    "DNI": "61079943",
    "NOMBRE Y APELLIDO": "CCALLO ANGULO, Ana Martina",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "1",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "1",
    "DESAPROBADAS": "5",
    "CONDICION": "DESAPROBADO"
  },
  "76160408": {
    "DNI": "76160408",
    "NOMBRE Y APELLIDO": "CHIPANA GUISPE, Brayan",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "13",
    "MS WORD": "16",
    "MS EXCEL": "14",
    "GESTION DE NEGOCIOS ": "13",
    "COMUNICACIÓN EFECTIVA": "15",
    "EFSRT": "14",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61195750": {
    "DNI": "61195750",
    "NOMBRE Y APELLIDO": "CORDOVA HUAMAN, David Fernando",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "19",
    "MS EXCEL": "19",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "17",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61304615": {
    "DNI": "61304615",
    "NOMBRE Y APELLIDO": "CROVETTO RAMIREZ, Gabriel Antonio",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "19",
    "MS EXCEL": "13",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "3",
    "DESAPROBADAS": "3",
    "CONDICION": "DESAPROBADO"
  },
  "70760732": {
    "DNI": "70760732",
    "NOMBRE Y APELLIDO": "DUEÑAS MEZA, Khell Mherlyn",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "19",
    "EFSRT": "NP",
    "APROBADAS": "5",
    "DESAPROBADAS": "1",
    "CONDICION": "DESAPROBADO"
  },
  "60804523": {
    "DNI": "60804523",
    "NOMBRE Y APELLIDO": "ECONEMA MEDINA, Kristy Fernanda",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "81059625": {
    "DNI": "81059625",
    "NOMBRE Y APELLIDO": "FERNANDEZ PEÑA, Carolina Ruth",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "60538093": {
    "DNI": "60538093",
    "NOMBRE Y APELLIDO": "GARCIA SOSA, Ruth Kely",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "19",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "19",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61835413": {
    "DNI": "61835413",
    "NOMBRE Y APELLIDO": "HERRERA CCOLQUI, Azumi Cielo",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "19",
    "MS EXCEL": "17",
    "GESTION DE NEGOCIOS ": "13",
    "COMUNICACIÓN EFECTIVA": "19",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "76978409": {
    "DNI": "76978409",
    "NOMBRE Y APELLIDO": "HERRERA MORALES, Wilman",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "43239986": {
    "DNI": "43239986",
    "NOMBRE Y APELLIDO": "HUARCAYA LOAYZA, Rosa Rocio",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "18",
    "MS EXCEL": "19",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "15",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "60859516": {
    "DNI": "60859516",
    "NOMBRE Y APELLIDO": "MAMANI COLQUE, Carlos Ivan Slim",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "15",
    "MS WORD": "13",
    "MS EXCEL": "13",
    "GESTION DE NEGOCIOS ": "15",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "13",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "29707536": {
    "DNI": "29707536",
    "NOMBRE Y APELLIDO": "MAMANI CURASI, Eleuterio Moises",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "9",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "1",
    "DESAPROBADAS": "5",
    "CONDICION": "DESAPROBADO"
  },
  "73999423": {
    "DNI": "73999423",
    "NOMBRE Y APELLIDO": "MANDUJANO TORRES, Luis Anthony",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61534453": {
    "DNI": "61534453",
    "NOMBRE Y APELLIDO": "MELENDEZ VELASQUEZ, Colin Baysheva",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "73533238": {
    "DNI": "73533238",
    "NOMBRE Y APELLIDO": "MIRANDA APAZA, Jordan Junior Jhonatan",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "9",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "1",
    "DESAPROBADAS": "5",
    "CONDICION": "DESAPROBADO"
  },
  "61555713": {
    "DNI": "61555713",
    "NOMBRE Y APELLIDO": "PALOMINO CHUNAPA, Evelin",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "60804572": {
    "DNI": "60804572",
    "NOMBRE Y APELLIDO": "PARDO HUAYABAN, Edwar Santiago",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "60859629": {
    "DNI": "60859629",
    "NOMBRE Y APELLIDO": "PEREZ CHANCHARIN, Zharick Rashel",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "NP",
    "APROBADAS": "5",
    "DESAPROBADAS": "1",
    "CONDICION": "DESAPROBADO"
  },
  "77430675": {
    "DNI": "77430675",
    "NOMBRE Y APELLIDO": "PINEDO MACUYAMA, Ruperto Andres",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "14",
    "MS WORD": "17",
    "MS EXCEL": "18",
    "GESTION DE NEGOCIOS ": "15",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "4",
    "DESAPROBADAS": "2",
    "CONDICION": "DESAPROBADO"
  },
  "61195603": {
    "DNI": "61195603",
    "NOMBRE Y APELLIDO": "ROJAS CHACON, Larry Miguel",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "20",
    "MS EXCEL": "17",
    "GESTION DE NEGOCIOS ": "14",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "NP",
    "APROBADAS": "5",
    "DESAPROBADAS": "1",
    "CONDICION": "DESAPROBADO"
  },
  "76374257": {
    "DNI": "76374257",
    "NOMBRE Y APELLIDO": "TAKORI TANYAKA, Katia Kassandra",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "13",
    "MS WORD": "15",
    "MS EXCEL": "17",
    "GESTION DE NEGOCIOS ": "13",
    "COMUNICACIÓN EFECTIVA": "15",
    "EFSRT": "13",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "63057243": {
    "DNI": "63057243",
    "NOMBRE Y APELLIDO": "VIDAL MACEDO, Jinny Jasmin",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "10",
    "MS WORD": "9",
    "MS EXCEL": "13",
    "GESTION DE NEGOCIOS ": "4",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "5",
    "DESAPROBADAS": "1",
    "CONDICION": "DESAPROBADO"
  },
  "61195949": {
    "DNI": "61195949",
    "NOMBRE Y APELLIDO": "APAZA SZABO, Danyelo Hunsan Kenyo",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "74434504": {
    "DNI": "74434504",
    "NOMBRE Y APELLIDO": "APUCUSI FLORES, Maria Esther",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61196243": {
    "DNI": "61196243",
    "NOMBRE Y APELLIDO": "AVEGAS CCAHUAYA, Alexander",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "15",
    "MS WORD": "18",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "15",
    "COMUNICACIÓN EFECTIVA": "17",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "71131544": {
    "DNI": "71131544",
    "NOMBRE Y APELLIDO": "AYUQUE PEREZ, Bettza",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "18",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "60973327": {
    "DNI": "60973327",
    "NOMBRE Y APELLIDO": "CHAPIAMA HOYOS, Jhared Aldair Edinho",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "15",
    "MS WORD": "19",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "19",
    "COMUNICACIÓN EFECTIVA": "15",
    "EFSRT": "15",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "60230489": {
    "DNI": "60230489",
    "NOMBRE Y APELLIDO": "CRUZ PALOMINO, Shomara Leny",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "19",
    "MS EXCEL": "18",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "15",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "60739491": {
    "DNI": "60739491",
    "NOMBRE Y APELLIDO": "DIAZ OROSCO, Joseph Nelson",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "0",
    "MS WORD": "0",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "62531531": {
    "DNI": "62531531",
    "NOMBRE Y APELLIDO": "DUEÑAS MEZA, Jhon Lee",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "NP",
    "APROBADAS": "5",
    "DESAPROBADAS": "1",
    "CONDICION": "DESAPROBADO"
  },
  "61195807": {
    "DNI": "61195807",
    "NOMBRE Y APELLIDO": "DUEÑAS MEZA, Josue Eulogio",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "17",
    "COMUNICACIÓN EFECTIVA": "14",
    "EFSRT": "15",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "60804819": {
    "DNI": "60804819",
    "NOMBRE Y APELLIDO": "ESCARCENA SUAREZ, Diego Arturo",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61195654": {
    "DNI": "61195654",
    "NOMBRE Y APELLIDO": "FRISANCHO CUNO, Sara Esther Maruja",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "62510714": {
    "DNI": "62510714",
    "NOMBRE Y APELLIDO": "HUILCAHUAMAN URQUIA, Dioni Kelvin",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "20",
    "MS EXCEL": "17",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "90151362": {
    "DNI": "90151362",
    "NOMBRE Y APELLIDO": "JORDAN RAMIREZ, Yardeli Melisa",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "0",
    "MS WORD": "0",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "61080059": {
    "DNI": "61080059",
    "NOMBRE Y APELLIDO": "LLANCO HUALLPA, Nayda Angelica",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "76963151": {
    "DNI": "76963151",
    "NOMBRE Y APELLIDO": "LLOCLLE CHARALLA, Rolando",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "13",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "46963029": {
    "DNI": "46963029",
    "NOMBRE Y APELLIDO": "MAMANI ATENCIO, Edalia Rosmedi",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "13",
    "MS WORD": "19",
    "MS EXCEL": "18",
    "GESTION DE NEGOCIOS ": "17",
    "COMUNICACIÓN EFECTIVA": "15",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "40306022": {
    "DNI": "40306022",
    "NOMBRE Y APELLIDO": "MAMANI UCHASARA, Helen Juddy",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "20",
    "MS EXCEL": "18",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "19",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "1296639": {
    "DNI": "1296639",
    "NOMBRE Y APELLIDO": "MEDINA FLORES, Cayetana",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "5",
    "MS WORD": "0",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "60859080": {
    "DNI": "60859080",
    "NOMBRE Y APELLIDO": "MEDRANO NARVAEZ, Tiffani Treyci",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "0",
    "MS WORD": "0",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "61304390": {
    "DNI": "61304390",
    "NOMBRE Y APELLIDO": "MORENO ROLIN, Neysi Betania",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "17",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "75676933": {
    "DNI": "75676933",
    "NOMBRE Y APELLIDO": "OLVEA TINCO, Alicia Karina",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "15",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61304513": {
    "DNI": "61304513",
    "NOMBRE Y APELLIDO": "SALVA QUISPE, Andress Katsuki",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "13",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "NP",
    "APROBADAS": "5",
    "DESAPROBADAS": "1",
    "CONDICION": "DESAPROBADO"
  },
  "74570157": {
    "DNI": "74570157",
    "NOMBRE Y APELLIDO": "SANDOVAL GARCIA, Yenifer Mayte",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61874659": {
    "DNI": "61874659",
    "NOMBRE Y APELLIDO": "SORIA INUMA, Wilder Eli",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "17",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "60804312": {
    "DNI": "60804312",
    "NOMBRE Y APELLIDO": "VALENZUELA MAYO, Dannery Yadira Xiomara",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "15",
    "MS WORD": "19",
    "MS EXCEL": "18",
    "GESTION DE NEGOCIOS ": "19",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "14",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "77023703": {
    "DNI": "77023703",
    "NOMBRE Y APELLIDO": "VARGAS TENAZOA, Scott Benny",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "72848894": {
    "DNI": "72848894",
    "NOMBRE Y APELLIDO": "VELA SORIA, Delcy Yadhira",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "18",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "NP",
    "APROBADAS": "5",
    "DESAPROBADAS": "1",
    "CONDICION": "DESAPROBADO"
  },
  "60804858": {
    "DNI": "60804858",
    "NOMBRE Y APELLIDO": "VILCA SURCO, Rafael Farid",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "18",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "05071589": {
    "DNI": "05071589",
    "NOMBRE Y APELLIDO": "ZEVALLOSVDA. DE MUÑANTE, Miriam Elvira",
    "TURNO": "MAÑANA",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "15",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61482048": {
    "DNI": "61482048",
    "NOMBRE Y APELLIDO": "ACOSTA CHURA, Adrian Erik",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "18",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "74032417": {
    "DNI": "74032417",
    "NOMBRE Y APELLIDO": "ALVAREZ REYNER, Alexandra Faviana",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "18",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "18",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "NP",
    "APROBADAS": "5",
    "DESAPROBADAS": "1",
    "CONDICION": "DESAPROBADO"
  },
  "60627111": {
    "DNI": "60627111",
    "NOMBRE Y APELLIDO": "ANCHELIA ASPAJO, Renzo Hayko",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "18",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61195570": {
    "DNI": "61195570",
    "NOMBRE Y APELLIDO": "BASCOPÉ GUZMÁN, Stiven Josué",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61387706": {
    "DNI": "61387706",
    "NOMBRE Y APELLIDO": "CACHIQUE TRIGOSO, Mariela Yanely",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "16",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "18",
    "COMUNICACIÓN EFECTIVA": "4",
    "EFSRT": "NP",
    "APROBADAS": "4",
    "DESAPROBADAS": "2",
    "CONDICION": "DESAPROBADO"
  },
  "61080138": {
    "DNI": "61080138",
    "NOMBRE Y APELLIDO": "CASANOVA HUAMAN, Jakelin Flor",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "16",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "2",
    "DESAPROBADAS": "4",
    "CONDICION": "DESAPROBADO"
  },
  "60804315": {
    "DNI": "60804315",
    "NOMBRE Y APELLIDO": "CHAPIAMA POLANCO, Katiuzka Malu",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "13",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "10",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "3",
    "DESAPROBADAS": "3",
    "CONDICION": "DESAPROBADO"
  },
  "63113288": {
    "DNI": "63113288",
    "NOMBRE Y APELLIDO": "CHAVEZ PASTOR, Ayko Eskarlet",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "15",
    "MS WORD": "15",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "18",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "77440328": {
    "DNI": "77440328",
    "NOMBRE Y APELLIDO": "DURAN AGUERO, Jocelyn Naina",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "18",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "75871984": {
    "DNI": "75871984",
    "NOMBRE Y APELLIDO": "FERNANDEZ CCOCCOSTO, Yeni Margoth",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "18",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "60973459": {
    "DNI": "60973459",
    "NOMBRE Y APELLIDO": "GALINDO CONCHA, Fabian Renzo",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "15",
    "MS WORD": "14",
    "MS EXCEL": "18",
    "GESTION DE NEGOCIOS ": "18",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "14",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "80537641": {
    "DNI": "80537641",
    "NOMBRE Y APELLIDO": "GONZALES GONZALES, Ruth",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "15",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "2",
    "DESAPROBADAS": "4",
    "CONDICION": "DESAPROBADO"
  },
  "73946528": {
    "DNI": "73946528",
    "NOMBRE Y APELLIDO": "GUTIERREZ MAMANI, Angie Stefany",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "19",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "10",
    "COMUNICACIÓN EFECTIVA": "18",
    "EFSRT": "NP",
    "APROBADAS": "4",
    "DESAPROBADAS": "2",
    "CONDICION": "DESAPROBADO"
  },
  "61786124": {
    "DNI": "61786124",
    "NOMBRE Y APELLIDO": "HUAMAN HAQQUEHUA, Ariana",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "16",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "18",
    "COMUNICACIÓN EFECTIVA": "18",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "44012307": {
    "DNI": "44012307",
    "NOMBRE Y APELLIDO": "LIMA PACCO, Veronica",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "15",
    "MS WORD": "17",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "40626377": {
    "DNI": "40626377",
    "NOMBRE Y APELLIDO": "LIZA TORRES, Sheyla Milagritos",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "18",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "10",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "3",
    "DESAPROBADAS": "3",
    "CONDICION": "DESAPROBADO"
  },
  "40626377_1": {
    "DNI": "40626377",
    "NOMBRE Y APELLIDO": "LOAYZA BERNAOLA, Nicolás",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "16",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "10",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "3",
    "DESAPROBADAS": "3",
    "CONDICION": "DESAPROBADO"
  },
  "75695904": {
    "DNI": "75695984",
    "NOMBRE Y APELLIDO": "LOPINTA AYMA, Rosa Liniet",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "0",
    "MS WORD": "0",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "80836847": {
    "DNI": "80836847",
    "NOMBRE Y APELLIDO": "MANUEL LOPEZ, Amorosa Katlen",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "17",
    "MS EXCEL": "18",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "72017120": {
    "DNI": "72017120",
    "NOMBRE Y APELLIDO": "MIRANDA CHAVEZ, Yndira Marymar",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "15",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "18",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "18",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "72464845": {
    "DNI": "72464845",
    "NOMBRE Y APELLIDO": "OSORIO CALDERÒN, Gerardo",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "19",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "10",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "3",
    "DESAPROBADAS": "3",
    "CONDICION": "DESAPROBADO"
  },
  "75676747": {
    "DNI": "75676747",
    "NOMBRE Y APELLIDO": "QQUENAYA CUTI, Jean Carlo",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "14",
    "MS WORD": "14",
    "MS EXCEL": "10",
    "GESTION DE NEGOCIOS ": "10",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "2",
    "DESAPROBADAS": "4",
    "CONDICION": "DESAPROBADO"
  },
  "61304537": {
    "DNI": "61304537",
    "NOMBRE Y APELLIDO": "QUISPE CONDORI, Belinda Zenaida",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "13",
    "MS WORD": "14",
    "MS EXCEL": "13",
    "GESTION DE NEGOCIOS ": "10",
    "COMUNICACIÓN EFECTIVA": "18",
    "EFSRT": "NP",
    "APROBADAS": "4",
    "DESAPROBADAS": "2",
    "CONDICION": "DESAPROBADO"
  },
  "61304022": {
    "DNI": "61304022",
    "NOMBRE Y APELLIDO": "QUISPE GONZALES, Giovana",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "13",
    "MS WORD": "14",
    "MS EXCEL": "13",
    "GESTION DE NEGOCIOS ": "10",
    "COMUNICACIÓN EFECTIVA": "18",
    "EFSRT": "NP",
    "APROBADAS": "5",
    "DESAPROBADAS": "1",
    "CONDICION": "DESAPROBADO"
  },
  "76172137": {
    "DNI": "76172137",
    "NOMBRE Y APELLIDO": "QUISPE QUISPE, Iveth Alexandra",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "18",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "17",
    "COMUNICACIÓN EFECTIVA": "17",
    "EFSRT": "NP",
    "APROBADAS": "5",
    "DESAPROBADAS": "1",
    "CONDICION": "DESAPROBADO"
  },
  "61835532": {
    "DNI": "61835532",
    "NOMBRE Y APELLIDO": "RAMOS TOREM, Dannait Daniela",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "47957823": {
    "DNI": "47957823",
    "NOMBRE Y APELLIDO": "RENGIFO URQUIA, Lizbeth Stefany",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "0",
    "MS WORD": "0",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "05777671": {
    "DNI": "05777671",
    "NOMBRE Y APELLIDO": "RODRIGUEZ HERNANDEZ, Reina Juliana",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "0",
    "MS WORD": "0",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "62020452": {
    "DNI": "62020452",
    "NOMBRE Y APELLIDO": "RODRIGUEZ VILARRUEL, Jotxu",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "18",
    "MS EXCEL": "18",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "62435637": {
    "DNI": "62435637",
    "NOMBRE Y APELLIDO": "ROJAS GUEVARA, Marvin Sneyder",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "NP",
    "APROBADAS": "5",
    "DESAPROBADAS": "1",
    "CONDICION": "DESAPROBADO"
  },
  "75828784": {
    "DNI": "75828784",
    "NOMBRE Y APELLIDO": "RUIZ SILVA, Estefita",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "18",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "15",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "76963195": {
    "DNI": "76963195",
    "NOMBRE Y APELLIDO": "SANDOVAL AHUANARI, Lorena",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "13",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "2",
    "DESAPROBADAS": "4",
    "CONDICION": "DESAPROBADO"
  },
  "23825642": {
    "DNI": "23825642",
    "NOMBRE Y APELLIDO": "TICONA OVIEDO, Celia",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "0",
    "MS WORD": "15",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "1",
    "DESAPROBADAS": "5",
    "CONDICION": "DESAPROBADO"
  },
  "60543123": {
    "DNI": "60543123",
    "NOMBRE Y APELLIDO": "VARGAS ACOSTUPA, Yunsuu Jaret",
    "TURNO": "TARDE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "17",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "18",
    "COMUNICACIÓN EFECTIVA": "18",
    "EFSRT": "17",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "63114001": {
    "DNI": "63114001",
    "NOMBRE Y APELLIDO": "BENITO BALCON, Yunsu",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "17",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61080228": {
    "DNI": "61080228",
    "NOMBRE Y APELLIDO": "CALISAYA RUCANA, Lizeth Lucero",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "0",
    "MS WORD": "0",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "72314208": {
    "DNI": "72314208",
    "NOMBRE Y APELLIDO": "CARRASCO SANCHEZ, Isabel Stephany",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "6",
    "MS WORD": "9",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "73071451": {
    "DNI": "73071451",
    "NOMBRE Y APELLIDO": "CHAMBI CCASA, Lisbeth",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "13",
    "MS WORD": "15",
    "MS EXCEL": "18",
    "GESTION DE NEGOCIOS ": "14",
    "COMUNICACIÓN EFECTIVA": "10",
    "EFSRT": "NP",
    "APROBADAS": "4",
    "DESAPROBADAS": "2",
    "CONDICION": "DESAPROBADO"
  },
  "09916376": {
    "DNI": "09916376",
    "NOMBRE Y APELLIDO": "CISNEROS CANDIA, Marisol Roxana",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "10",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "3",
    "DESAPROBADAS": "3",
    "CONDICION": "DESAPROBADO"
  },
  "62531311": {
    "DNI": "62531311",
    "NOMBRE Y APELLIDO": "COAPAZA TURPO, Tony Beker",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "17",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "18",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "40806615": {
    "DNI": "40806615",
    "NOMBRE Y APELLIDO": "DIAZ DIAZ, Annie Sonia",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "9",
    "MS WORD": "0",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "77231442": {
    "DNI": "77231442",
    "NOMBRE Y APELLIDO": "DURAND VELASQUEZ, Nashira Danushka",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "60973842": {
    "DNI": "60973842",
    "NOMBRE Y APELLIDO": "ECONEMA HUAHOJEHUA, Robert Williams Aduardo",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "8",
    "MS WORD": "0",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "60804636": {
    "DNI": "60804636",
    "NOMBRE Y APELLIDO": "FLORES ESCOBAR, Brenda Emperatriz",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "75486277": {
    "DNI": "75486277",
    "NOMBRE Y APELLIDO": "FLORES MONCADA, Wendy Gisela",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "77171618": {
    "DNI": "77171618",
    "NOMBRE Y APELLIDO": "GONZALES LUNA, Julisa Leonor",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "19",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "18",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "46866927": {
    "DNI": "46866927",
    "NOMBRE Y APELLIDO": "GONZALO CHUCO, Sonia Lisbeth",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "13",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "10",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "3",
    "DESAPROBADAS": "3",
    "CONDICION": "DESAPROBADO"
  },
  "61304168": {
    "DNI": "61304168",
    "NOMBRE Y APELLIDO": "GUEVARA BECERRA, Danitza Xiomara",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "40085356": {
    "DNI": "40085356",
    "NOMBRE Y APELLIDO": "HUILCAHUAMAN ROLIN, Ruth Maria",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "15",
    "MS WORD": "18",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "62708818": {
    "DNI": "62708818",
    "NOMBRE Y APELLIDO": "HURTADO LOAYZA, Briana Sheyla",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "12",
    "MS WORD": "13",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "2",
    "DESAPROBADAS": "4",
    "CONDICION": "DESAPROBADO"
  },
  "44663778": {
    "DNI": "44663778",
    "NOMBRE Y APELLIDO": "IREY CAMENO, Anoshka Violeta",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "18",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61195948": {
    "DNI": "61195948",
    "NOMBRE Y APELLIDO": "LOPEZ MORENO, Hadami Adamaris",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "75695904": {
    "DNI": "75695904",
    "NOMBRE Y APELLIDO": "LOPINTA AYMA, Rosa Liniet",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "46531100": {
    "DNI": "46531100",
    "NOMBRE Y APELLIDO": "MARTINEZ VARGAS, Sandra",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "18",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "10",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "3",
    "DESAPROBADAS": "3",
    "CONDICION": "DESAPROBADO"
  },
  "71238590": {
    "DNI": "71238590",
    "NOMBRE Y APELLIDO": "MORENO GONGORA, Keyko Briyith",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "45739680": {
    "DNI": "45739680",
    "NOMBRE Y APELLIDO": "MORENO PEREZ, Rosa Yovana",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "0",
    "MS WORD": "4",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "48666105": {
    "DNI": "48666105",
    "NOMBRE Y APELLIDO": "PACHACUTE GRANUEL, Sheyla Lisset",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "4",
    "MS WORD": "20",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "75227592": {
    "DNI": "75227592",
    "NOMBRE Y APELLIDO": "PACHACUTEC BAEZ, Daniel",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "04828832": {
    "DNI": "04828832",
    "NOMBRE Y APELLIDO": "PALOMINO LA SERNA, Justiniano",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "16",
    "MS WORD": "19",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "10",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "3",
    "DESAPROBADAS": "3",
    "CONDICION": "DESAPROBADO"
  },
  "61886128": {
    "DNI": "61886128",
    "NOMBRE Y APELLIDO": "PEREYRA ARIRAMA, Heidy Darianna",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "18",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "72468553": {
    "DNI": "72468553",
    "NOMBRE Y APELLIDO": "PEREZ BARDALES, Jorge Greennwich",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61304663": {
    "DNI": "61304663",
    "NOMBRE Y APELLIDO": "PFORO PUMA, Fayluz Shiary",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "18",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "44755497": {
    "DNI": "44755497",
    "NOMBRE Y APELLIDO": "RIVERA SALAZAR, Evelyn Janet",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "20",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "76281953": {
    "DNI": "76281953",
    "NOMBRE Y APELLIDO": "SANCHEZ FLORES, Genesis Anadalay",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "15",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "NP",
    "APROBADAS": "5",
    "DESAPROBADAS": "1",
    "CONDICION": "DESAPROBADO"
  },
  "45854750": {
    "DNI": "45854750",
    "NOMBRE Y APELLIDO": "TORRES CORDOVA, Yanett Bruna",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "0",
    "MS WORD": "0",
    "MS EXCEL": "0",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "0",
    "DESAPROBADAS": "6",
    "CONDICION": "DESAPROBADO"
  },
  "29648556": {
    "DNI": "29648556",
    "NOMBRE Y APELLIDO": "VILCA MANRIQUE, Daissy Daniela",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "72893668": {
    "DNI": "72893668",
    "NOMBRE Y APELLIDO": "YAMPI MENDEZ, Juan Pablo",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "17",
    "MS WORD": "18",
    "MS EXCEL": "14",
    "GESTION DE NEGOCIOS ": "0",
    "COMUNICACIÓN EFECTIVA": "0",
    "EFSRT": "NP",
    "APROBADAS": "3",
    "DESAPROBADAS": "3",
    "CONDICION": "DESAPROBADO"
  },
  "40938364": {
    "DNI": "40938364",
    "NOMBRE Y APELLIDO": "YONEKURA UPIACHIHUA, Silvia Ruth",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "19",
    "MS WORD": "20",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  },
  "61388379": {
    "DNI": "61388379",
    "NOMBRE Y APELLIDO": "YUPANQUI ORBE, Stephie Yovana",
    "TURNO": "NOCHE",
    "ESTUDIO DE SISTEMAS OPERATIVOS": "14",
    "MS WORD": "17",
    "MS EXCEL": "20",
    "GESTION DE NEGOCIOS ": "20",
    "COMUNICACIÓN EFECTIVA": "20",
    "EFSRT": "20",
    "APROBADAS": "6",
    "DESAPROBADAS": "0",
    "CONDICION": "APROBADO"
  }
};

